/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bibliotecaAdministrador.Libro;

import bibliotecaAdministrador.ConexionBD;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import javax.swing.JOptionPane;

/**
 *
 * @author g
 */
public class Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Actualizar
     */
    ResultSet res;
    ConexionBD conecta;
    private String id;
    public void setNombre(String id){
        this.id=id;
        txtID.setText(id);
        try {
            conecta = new ConexionBD();
            String sql="SELECT l.titulo, g.descripcion FROM libros l INNER JOIN generos g ON l.id_genero=g.id_genero WHERE l.id_libro="+Integer.parseInt(id);
            res = conecta.consultar(sql);
            while(res.next()){
                txtTitulo.setText(res.getString("titulo"));
                cmbGeneros.setSelectedItem(res.getString("descripcion"));
            }
        } 
        catch (Exception e) {
        }
    }
    
    public Actualizar() {
        initComponents();
        llenarGenero();
        txtID.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setTitle("BIBLIOTECA");
        this.setIconImage(getIconImage());
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/library.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLib = new javax.swing.JPanel();
        lbltit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cmbGeneros = new javax.swing.JComboBox();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltit.setText("ACTUALIZAR LIBRO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Titulo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Género");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regresar.png"))); // NOI18N
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cmbGeneros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion" }));

        javax.swing.GroupLayout panelLibLayout = new javax.swing.GroupLayout(panelLib);
        panelLib.setLayout(panelLibLayout);
        panelLibLayout.setHorizontalGroup(
            panelLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(panelLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(67, 67, 67)
                .addGroup(panelLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTitulo)
                    .addComponent(cmbGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibLayout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibLayout.createSequentialGroup()
                        .addComponent(lbltit)
                        .addGap(218, 218, 218))))
        );
        panelLibLayout.setVerticalGroup(
            panelLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lbltit)
                .addGap(38, 38, 38)
                .addGroup(panelLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panelLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Libros lib = new Libros();
        lib.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(!txtTitulo.getText().equals("") && cmbGeneros.getSelectedIndex()>0 && !txtID.getText().equals("")){
            ResultSet resG;
            String idG="", idE="", idC="";
            conecta = new ConexionBD();
            String sql ="SELECT g.id_genero FROM generos g WHERE g.descripcion='"+cmbGeneros.getSelectedItem()+"'";
            System.out.println(sql);
            resG = conecta.consultar(sql);
            try{
                while(resG.next()){
                    idG=resG.getString("id_genero");
                    System.out.println("hola1");
                }
                System.out.println(idG);
            }catch(Exception e){
                System.out.println("error al consultar ids para los libros: "+e.getMessage());
            }
            String sqlactualiza = "UPDATE libros set titulo='"+txtTitulo.getText()+"',id_genero="+Integer.parseInt(idG)+" where id_libro='"+txtID.getText()+"'";
            System.out.println(sqlactualiza);
            try{
                conecta.operacionesAMB(sqlactualiza);
                JOptionPane.showMessageDialog(null, "Exito al actualizar informacion");
                txtID.setText("");
                txtTitulo.setText("");
                cmbGeneros.setSelectedIndex(0);
            }catch(SQLException ex){
                System.out.println("Error al actualizar libro error sql"+ex.getMessage());
                JOptionPane.showMessageDialog(null, "No se pudo actualizar el registro en libros error sql: "+ex.getMessage());
            }
            catch(Exception e){
                System.out.println("error al actualizar informacion de libros: "+e.getMessage());
                JOptionPane.showMessageDialog(null, "Error al actualizar informacion");
            }finally{
                conecta.cerrar();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por Favor verifica que todos los campos esten llenos y de buscar al autor");
        }
        /*panelL.remove(jtLibros);
        tablaL();
        repaint();*/
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    void llenarGenero(){
        try {
            conecta = new ConexionBD();
            String sqlConsulta="SELECT descripcion FROM generos";
            res = conecta.consultar(sqlConsulta);
            while(res.next()){
                cmbGeneros.addItem(res.getString("descripcion"));
            }
        } catch (Exception e) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //UIManager.setLookAndFeel( new FlatLightLaf() );
            FlatMacLightLaf.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox cmbGeneros;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel lbltit;
    private javax.swing.JPanel panelLib;
    private javax.swing.JTextField txtID;
    public javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
