/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bibliotecaAdministrador.Devolucion;

import bibliotecaAdministrador.ConexionBD;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import javax.swing.JOptionPane;

/**
 *
 * @author g
 */
public class Guardar extends javax.swing.JFrame {

    /**
     * Creates new form Guardar
     */
    ConexionBD conecta;
    ResultSet res;
    public Guardar() {
        initComponents();
        txtNom.setEditable(false);
        txtTel.setEditable(false);
        txtTitulo.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("BIBLIOTECA");
        this.setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/library.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarUsuario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarLibro = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnDevolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRAR DEVOLUCIÓN DE LIBRO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Datos del Usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No.Control Usuario");

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Telefono");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nombre");

        btnBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscarUsuario.setText("BUSCAR USUARIO");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Datos del Libro");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Codigo Copia");

        txtLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLibroKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Titulo Libro");

        btnBuscarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscarLibro.setText("BUSCAR LIBRO    ");
        btnBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLibroActionPerformed(evt);
            }
        });

        btnDevolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnDevolver.setText("GUARDAR");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regresar.png"))); // NOI18N
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(328, 328, 328))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnBuscarUsuario)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(39, 39, 39)
                .addComponent(btnBuscarLibro)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDevolver)
                .addGap(18, 54, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // TODO add your handling code here:
        if(!txtUsuario.getText().equals("")){
            ResultSet res;
            conecta = new ConexionBD();
            try{
                String sqlUsuario="SELECT id_usuario, CONCAT(nombre,' ', ap,' ', am) AS nombre, telefono from usuarios where id_usuario="+Integer.parseInt(txtUsuario.getText())+"";
                res = conecta.consultar(sqlUsuario);
                if(res.next()){
                    JOptionPane.showMessageDialog(null, "Usuario Encontrado");
                    txtNom.setText(res.getString("nombre"));
                    txtTel.setText(res.getString("telefono"));
                    System.out.println(res.getString("id_usuario"));
                    //txtIdPrestamo.setText(res.getString("id_usuario"));
                }
                else{
                    JOptionPane.showMessageDialog(null, "Usuario no encontrado, intenta de nuevo");
                    txtUsuario.setText("");
                }
                System.out.println(sqlUsuario);
            }catch(SQLException ex){
                System.out.println("error sql al buscar usuario: "+ex.getMessage());
            }
            catch(Exception e){
                System.out.println("error al buscar usuario: "+e.getMessage());
            }finally{
                conecta.cerrar();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por Favor Ingresa el Numero de Control del Usuario");
        }
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void txtLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLibroKeyTyped
        // TODO add your handling code here:
        /*char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }*/
    }//GEN-LAST:event_txtLibroKeyTyped

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        // TODO add your handling code here:
        if(!txtLibro.getText().equals("")){
            ResultSet res;
            conecta = new ConexionBD();
            try{
                String sqlLibro="SELECT l.id_libro, l.titulo from libros l INNER JOIN copias c ON c.id_libro=l.id_libro where c.codigo_copia='"+txtLibro.getText()+"'";
                res = conecta.consultar(sqlLibro);
                if(res.next()){
                    JOptionPane.showMessageDialog(null, "Libro Encontrado");
                    System.out.println(res.getString("id_libro"));
                    txtTitulo.setText(res.getString("titulo"));
                    //txtIdLibro.setText(res.getString("id_libro"));
                }
                else{
                    JOptionPane.showMessageDialog(null, "Libro no encontrado, intenta de nuevo");
                    txtLibro.setText("");
                }
                System.out.println(sqlLibro);
            }catch(Exception e){
                System.out.println("error al buscar libro: "+e.getMessage());
            }finally{
                conecta.cerrar();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Por Favor ingresa el codigo de copia del Libro");
        }
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // TODO add your handling code here:
        //conecta = new ConexionBD();
        /*if(!txtUsuario.getText().equals("") && !txtLibro.getText().equals("")){
            //conecta = new ConexionBD();
            conecta = new ConexionBD();
            ResultSet res, resIds;
            //String sqlConsulta="SELECT p.* FROM prestamos p, usuarios u, libros l, estados e WHERE l.titulo='"+txtLibro.getText()+"' and p.id_usuario=u.id_usuario and p.id_libro=l.id_libro and CONCAT(u.nombre,' ',u.ap,' ',u.am)='"+txtUsuario.getText()+"' and p.id_estado=e.id_estado and e.descripcion='Activo'";
            //String sqlConsulta="SELECT p.* FROM prestamos p, usuarios u, copias c, estados e WHERE c.id_copia=(SELECT id_copia from copias where c.codigo_copia='"+txtLibro.getText()+"') and p.id_usuario=u.id_usuario and p.id_copia=c.id_copia and u.id_usuario='"+Integer.parseInt(txtUsuario.getText())+"' and p.id_estado=e.id_estado and e.descripcion='Activo'";
            //String sqlConsulta="SELECT p.id_prestamo FROM prestamos p, usuarios u, copias c, estados e WHERE c.codigo_copia='"+txtLibro.getText()+"' and p.id_usuario=u.id_usuario and p.id_copia=c.id_copia and u.id_usuario='"+Integer.parseInt(txtUsuario.getText())+"' and p.id_estado=e.id_estado and e.descripcion='Activo'";
            String sqlConsulta="SELECT p.id_prestamo\n" +
            "FROM prestamos p\n" +
            "INNER JOIN usuarios u ON p.id_usuario = u.id_usuario\n" +
            "INNER JOIN copias c ON p.id_copia = c.id_copia\n" +
            "INNER JOIN estados e ON p.id_estado = e.id_estado\n" +
            "WHERE c.codigo_copia = '"+txtLibro.getText()+"' AND u.id_usuario = '"+txtUsuario.getText()+"' AND e.descripcion = 'Activo';";
            System.out.println(sqlConsulta);
            res=conecta.consultar(sqlConsulta);
            try {
                if(res.next()){
                    String idUsuario="", idCopia="", sqlIds="";
                    sqlIds="SELECT u.id_usuario, c.id_copia from usuarios u, copias c where u.id_usuario='"+Integer.parseInt(txtUsuario.getText())+"' and c.codigo_copia='"+txtLibro.getText()+"'";
                    resIds=conecta.consultar(sqlIds);
                    while(resIds.next()){
                        idUsuario=resIds.getString("id_usuario");
                        idCopia=resIds.getString("id_copia");
                    }
                    //String sqlAlta="INSERT INTO devoluciones VALUES(null, "+Integer.parseInt(idUsuario)+", "+Integer.parseInt(idLibro)+", now())";
                    //String sqlUpdate="UPDATE prestamos SET id_estado=(SELECT id_estado FROM estados where descripcion='Finalizado') where id_usuario="+Integer.parseInt(idUsuario)+" and id_libro="+Integer.parseInt(idLibro);
                    //System.out.println(sqlAlta);
                    //conecta.operacionesAMB(sqlAlta);
                    realizarDevolucion(Integer.parseInt(idUsuario), Integer.parseInt(idCopia));
                    //conecta.operacionesAMB(sqlUpdate);
                    JOptionPane.showMessageDialog(null, "Devolucion exitosa");
                    panelD.remove(jtDevoluciones);
                    tablaD();
                    repaint();
                }
                else{
                    JOptionPane.showMessageDialog(null, "No puedes devolver el libro porque no tienes un prestamo con ese libro");
                    txtUsuario.setText("");
                    txtLibro.setText("");
                }
            }catch(SQLException ex){
                System.out.println("Error al insertar devolucion en sqlexception"+ex.getMessage());
                JOptionPane.showMessageDialog(null, "No se pudo realizar el registro en devoluciones error sql: "+ex.getMessage());
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se pudo devolver el libro");
                System.out.println("No se pudo devolver el libro: "+e.getMessage());
            }finally{
                conecta.cerrar();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor llena los campos");
        }*/
        if(!txtUsuario.getText().equals("") && !txtLibro.getText().equals("")){
            conecta = new ConexionBD();
            String sqlConsulta="SELECT p.id_prestamo, c.id_copia\n" +
            "FROM prestamos p\n" +
            "INNER JOIN usuarios u ON p.id_usuario = u.id_usuario\n" +
            "INNER JOIN copias c ON p.id_copia = c.id_copia\n" +
            "INNER JOIN estados e ON p.id_estado = e.id_estado\n" +
            "WHERE c.codigo_copia = '"+txtLibro.getText()+"' AND u.id_usuario = '"+txtUsuario.getText()+"' AND e.descripcion = 'Activo';";
            res = conecta.consultar(sqlConsulta);
            System.out.println(sqlConsulta);
            try {
                if(res.next()){
                    int idCopia=res.getInt("id_copia");
                    int idUser=Integer.parseInt(txtUsuario.getText());
                    realizarDevolucion(idUser, idCopia);
                    JOptionPane.showMessageDialog(null, "Devolución Exitosa");
                    txtLibro.setText("");
                    txtNom.setText("");
                    txtTel.setText("");
                    txtTitulo.setText("");
                    txtUsuario.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "No puedes devolver el libro ya que no tienes un prestamo con ese libro");
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Devoluciones dev = new Devoluciones();
        dev.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void realizarDevolucion(int idUsuario, int idCopia) {
        try {
            conecta = new ConexionBD();
            CallableStatement cs = conecta.conn.prepareCall("{call devolucion(?, ?, ?)}");
            cs.setInt(1, idUsuario);
            cs.setInt(2, idCopia);
            cs.registerOutParameter(3, Types.VARCHAR);

            // Ejecutar el procedimiento almacenado
            cs.execute();

            // Obtener el mensaje de la devolución
            String mensaje = cs.getString(3);
            //System.out.println("Mensaje: " + mensaje);
            JOptionPane.showMessageDialog(null, mensaje);

            cs.close();
        }catch(SQLException ex){
            System.out.println("Error al insertar devolucion error sql"+ex.getMessage());
            JOptionPane.showMessageDialog(null, "No se pudo realizar el registro en devoluciones error sql: "+ex.getMessage());
        } 
        catch (Exception e) {
            System.out.println("Error al realizar la devolución: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Eror al realizar devolucion.");
        }
        /*finally{
            conecta.cerrar();
        }*/
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //UIManager.setLookAndFeel( new FlatLightLaf() );
            FlatMacLightLaf.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guardar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtLibro;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
