/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bibliotecaAdministrador.Prestamo;

import bibliotecaAdministrador.ConexionBD;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import javax.swing.JOptionPane;

/**
 *
 * @author g
 */
public class Guardar extends javax.swing.JFrame {

    /**
     * Creates new form Guardar
     */
    ConexionBD conecta;
    ResultSet res;
    public Guardar() {
        initComponents();
        txtNom.setEditable(false);
        txtTel.setEditable(false);
        txtTitulo.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("BIBLIOTECA");
        this.setIconImage(getIconImage());
    }

    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/library.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        cmbCopias = new javax.swing.JComboBox();
        btnBuscarLibro = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRAR NUEVO PRESTAMO");

        jLabel2.setText("Datos del Libro");

        jLabel3.setText("Codigo del Libro");

        jLabel4.setText("Titulo");

        jLabel5.setText("Datos del Usuario");

        jLabel6.setText("Nombre");

        jLabel7.setText("Telefono");

        btnBuscarUsuario.setBackground(new java.awt.Color(102, 153, 255));
        btnBuscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscarUsuario.setText("BUSCAR USUARIO");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        jLabel8.setText("No. Control");

        jLabel9.setText("Copias Disponibles");

        cmbCopias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion" }));

        btnBuscarLibro.setBackground(new java.awt.Color(102, 153, 255));
        btnBuscarLibro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscarLibro.setText("BUSCAR LIBRO");
        btnBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLibroActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regresar.png"))); // NOI18N
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(24, 24, 24)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTitulo)
                                    .addComponent(txtLibro)
                                    .addComponent(cmbCopias, 0, 275, Short.MAX_VALUE))
                                .addGap(217, 217, 217))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBuscarUsuario)
                                        .addGap(285, 285, 285))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(343, 343, 343))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(281, 281, 281))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(329, 329, 329))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(90, 90, 90))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel8))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtNom)
                                                    .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                                    .addComponent(txtUsuario))))
                                        .addGap(219, 219, 219))))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(356, 356, 356))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(btnBuscarUsuario)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(cmbCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarLibro)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // TODO add your handling code here:
        if(!txtUsuario.getText().equals("")){
            ResultSet res;
            conecta = new ConexionBD();
            try{
                String sqlUsuario="SELECT id_usuario, CONCAT(nombre,' ', ap,' ', am) AS nombre, telefono from usuarios where id_usuario="+Integer.parseInt(txtUsuario.getText())+"";
                res = conecta.consultar(sqlUsuario);
                if(res.next()){
                    JOptionPane.showMessageDialog(null, "Usuario Encontrado");
                    txtNom.setText(res.getString("nombre"));
                    txtTel.setText(res.getString("telefono"));
                    System.out.println(res.getString("id_usuario"));
                    //txtIdPrestamo.setText(res.getString("id_usuario"));
                }
                else{
                    JOptionPane.showMessageDialog(null, "Usuario no encontrado, intenta de nuevo");
                    txtUsuario.setText("");
                }
                System.out.println(sqlUsuario);
            }catch(SQLException ex){
                System.out.println("error sql al buscar usuario: "+ex.getMessage());
            }
            catch(Exception e){
                System.out.println("error al buscar usuario: "+e.getMessage());
            }finally{
                conecta.cerrar();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por Favor Ingresa el nombre completo del Usuario");
        }
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        // TODO add your handling code here:
        // Supongamos que tienes un JComboBox llamado cmbCopias
        cmbCopias.removeAllItems();
        cmbCopias.addItem("Seleccione una opcion");
        if(!txtLibro.getText().equals("")){
            ResultSet res, res2;
            conecta = new ConexionBD();
            try{
                String sqlLibro="SELECT id_libro, titulo from libros where id_libro='"+Integer.parseInt(txtLibro.getText())+"'";
                res = conecta.consultar(sqlLibro);
                if(res.next()){
                    JOptionPane.showMessageDialog(null, "Libro Encontrado");
                    txtTitulo.setText(res.getString("titulo"));
                    System.out.println(res.getString("id_libro"));
                    //txtIdLibro.setText(res.getString("id_libro"));
                    String sqlCopia="SELECT c.codigo_copia FROM copias c INNER JOIN estados e ON c.id_estado=e.id_estado where id_libro="+Integer.parseInt(txtLibro.getText())+" and e.descripcion='Disponible'";
                    res2 = conecta.consultar(sqlCopia);
                    while(res2.next()){
                        cmbCopias.addItem(res2.getString("codigo_copia"));
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Libro no encontrado, intenta de nuevo");
                    txtLibro.setText("");
                }
                System.out.println(sqlLibro);
            }catch(Exception e){
                System.out.println("error al buscar libro: "+e.getMessage());
            }finally{
                conecta.cerrar();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Por Favor ingresa el nombre del autor a buscar");
        }
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!txtUsuario.getText().equals("") && !txtLibro.getText().equals("") && cmbCopias.getSelectedIndex() > 0){
            ResultSet res;
            String idC="",idE="",idL="", desc="";
            conecta = new ConexionBD();
            //String sql="SELECT u.id_usuario, c.id_copia, e.id_estado, (SELECT descripcion FROM estados e INNER JOIN copias c ON c.id_estado=e.id_estado where c.codigo_copia='"+cmbCopias.getSelectedItem().toString()+"') as descripcion from usuarios u, copias c, estados e where u.id_usuario='"+Integer.parseInt(txtUsuario.getText())+"' and c.id_libro='"+Integer.parseInt(txtLibro.getText())+"' and e.descripcion='Activo'";
            //String sql="SELECT id_copia, id_libro, (SELECT id_estado FROM estados where descripcion='Activo') as id_estado,(SELECT e.descripcion FROM estados e INNER JOIN copias c ON c.id_estado=e.id_estado WHERE c.codigo_copia='"+cmbCopias.getSelectedItem().toString()+"') AS descripcion FROM copias WHERE codigo_copia='"+cmbCopias.getSelectedItem().toString()+"'";
             String sql = "SELECT p.id_copia, p.id_libro, " +
             " (SELECT id_estado FROM estados WHERE descripcion='Activo') AS id_estado, " +
             " (SELECT e.descripcion FROM estados e " +
             " INNER JOIN copias p ON p.id_estado=e.id_estado AND p.codigo_copia='" + cmbCopias.getSelectedItem().toString() + "') AS descripcion " +
             " FROM copias p WHERE p.codigo_copia='" + cmbCopias.getSelectedItem().toString() + "'";

            System.out.println(sql);
            res = conecta.consultar(sql);
            try{
                while(res.next()){
                    idC=res.getString("id_copia");
                    idL=res.getString("id_libro");
                    idE=res.getString("id_estado");
                    desc=res.getString("descripcion");
                }
                System.out.println(idC+" "+idE+" "+idL+" "+desc);
            }catch(Exception e){
                System.out.println("Error al obtener los ids para guardar prestamo: "+e.getMessage());
            }
            if(!desc.equals("Solo consulta")){
                //String sqlAlta="INSERT INTO prestamos VALUES(null,"+Integer.parseInt(idU)+","+Integer.parseInt(idL)+","+Integer.parseInt(idE)+",now(), now(), 0)";
                //System.out.println(sqlAlta);
                    try{
                        //conecta.operacionesAMB(sqlAlta);
                        //JOptionPane.showMessageDialog(null, "Registro Exitoso");
                        realizarPrestamo(Integer.parseInt(txtUsuario.getText()),Integer.parseInt(idC), Integer.parseInt(idL), Integer.parseInt(idE));
                        txtLibro.setText("");
                        txtUsuario.setText("");
                        txtNom.setText("");
                        txtTel.setText("");
                        txtTitulo.setText("");
                        cmbCopias.setSelectedIndex(0);
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Error al realizar registro");
                        System.out.println("Error al realizar registro prestamo llamando al procedure: "+e.getMessage());
                    }finally{
                        conecta.cerrar();
                    }
            }else{
                JOptionPane.showMessageDialog(null, "Lo sentimos el libro que quieres solo es de consulta");
                txtLibro.setText("");
                txtUsuario.setText("");
                }
        }else{
            JOptionPane.showMessageDialog(null, "Por Favor llena los campos y verifica que exista el usuario y el libro");
        }
            /*String sqlAlta="INSERT INTO prestamos VALUES(null,"+Integer.parseInt(idU)+","+Integer.parseInt(idL)+","+Integer.parseInt(idE)+",now(), now(), 0)";
            System.out.println(sqlAlta);
            try{
                conecta.operacionesAMB(sqlAlta);
                JOptionPane.showMessageDialog(null, "Registro Exitoso");
                txtLibro.setText("");
                txtUsuario.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error al realizar registro");
                System.out.println("Error al realizar registro prestamo: "+e.getMessage());
            }finally{
                conecta.cerrar();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por Favor llena los campos y verifica que exista el usuario y el libro");
        }
        panelP.remove(jtPrestamos);
        tablaP();
        repaint();*/
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Prestamos pres = new Prestamos();
        pres.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void realizarPrestamo(int idUsuario, int idCopia, int idLibro, int idEstado) {
    try {
        conecta = new ConexionBD();
        // Preparar la llamada al procedimiento almacenado
        String procedimiento = "{call RealizarPrestamo(?, ?, ?, ?, ?)}";
        CallableStatement cs = conecta.conn.prepareCall(procedimiento);

        // Establecer los parámetros del procedimiento almacenado
        cs.setInt(1, idUsuario);
        cs.setInt(2, idCopia);
        cs.setInt(3, idLibro);
        cs.setInt(4, idEstado);
        cs.registerOutParameter(5, Types.VARCHAR);

        // Ejecutar el procedimiento almacenado
        cs.execute();
        // Obtener el mensaje de salida del procedimiento
        String mensaje = cs.getString(5);
        JOptionPane.showMessageDialog(null, mensaje);

        // Cerrar el CallableStatement
        cs.close();
        //txtLibro.setText("");
        //txtUsuario.setText("");
        //JOptionPane.showMessageDialog(null, "Registro Exitoso");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al realizar el registro del préstamo");
        System.out.println("Error al realizar registro prestamo: " + e.getMessage());
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error al realizar prestamo. ");
    }
    finally{
        conecta.cerrar();
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //UIManager.setLookAndFeel( new FlatLightLaf() );
            FlatMacLightLaf.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guardar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JComboBox cmbCopias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtLibro;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
